# Generated by Django 5.0.2 on 2024-03-28 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AreaSido",
            fields=[
                (
                    "sido_code",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="AreaSigungu",
            fields=[
                (
                    "sigungu_code",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=10)),
                (
                    "sido_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="regions.areasido",
                    ),
                ),
            ],
        ),
    ]
