# Generated by Django 5.0.2 on 2024-03-16 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Shelter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("facility_name", models.CharField(max_length=100)),
                ("address", models.CharField(max_length=200)),
                ("location", models.CharField(max_length=3)),
                ("area", models.DecimalField(decimal_places=2, max_digits=10)),
                ("capacity", models.IntegerField()),
            ],
        ),
    ]
