# Generated by Django 5.0.2 on 2024-03-16 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shelterdb", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shelter",
            name="area",
            field=models.IntegerField(),
        ),
    ]
